//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        public static System.Drawing.Bitmap lizard
        {
            get
            {
                object obj = ResourceManager.GetObject("lizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ninja_white_icon
        {
            get
            {
                object obj = ResourceManager.GetObject("ninja_white_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap p5
        {
            get
            {
                object obj = ResourceManager.GetObject("p5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap p6
        {
            get
            {
                object obj = ResourceManager.GetObject("p6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pCaptain
        {
            get
            {
                return ResourceManager.GetString("pCaptain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pCards
        {
            get
            {
                return ResourceManager.GetString("pCards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pEL
        {
            get
            {
                return ResourceManager.GetString("pEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pGoals
        {
            get
            {
                return ResourceManager.GetString("pGoals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pHeight
        {
            get
            {
                return ResourceManager.GetString("pHeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pHL
        {
            get
            {
                return ResourceManager.GetString("pHL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pNo
        {
            get
            {
                return ResourceManager.GetString("pNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pNumber
        {
            get
            {
                return ResourceManager.GetString("pNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pScreen
        {
            get
            {
                return ResourceManager.GetString("pScreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pTitle
        {
            get
            {
                return ResourceManager.GetString("pTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pWidth
        {
            get
            {
                return ResourceManager.GetString("pWidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pYes
        {
            get
            {
                return ResourceManager.GetString("pYes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sAgainst
        {
            get
            {
                return ResourceManager.GetString("sAgainst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sDiff
        {
            get
            {
                return ResourceManager.GetString("sDiff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sDraw
        {
            get
            {
                return ResourceManager.GetString("sDraw", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings
        {
            get
            {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings2
        {
            get
            {
                object obj = ResourceManager.GetObject("settings2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sFor
        {
            get
            {
                return ResourceManager.GetString("sFor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sGoals
        {
            get
            {
                return ResourceManager.GetString("sGoals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sLoss
        {
            get
            {
                return ResourceManager.GetString("sLoss", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sLosser
        {
            get
            {
                return ResourceManager.GetString("sLosser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sOverall
        {
            get
            {
                return ResourceManager.GetString("sOverall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sPen
        {
            get
            {
                return ResourceManager.GetString("sPen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sSideAway
        {
            get
            {
                return ResourceManager.GetString("sSideAway", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sSideHome
        {
            get
            {
                return ResourceManager.GetString("sSideHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sTact
        {
            get
            {
                return ResourceManager.GetString("sTact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sWin
        {
            get
            {
                return ResourceManager.GetString("sWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sWinner
        {
            get
            {
                return ResourceManager.GetString("sWinner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string wMsg
        {
            get
            {
                return ResourceManager.GetString("wMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string wTitle
        {
            get
            {
                return ResourceManager.GetString("wTitle", resourceCulture);
            }
        }
    }
}
